language: python
python:
    - "3.9"
services:
    - postgresql
env:
    global:
    - DJANGO_SECRET_KEY="#bi^q(lytip$+3bj-z-23@6tds)5$fsgi0t^8m_(yg%8rjobc*"
    - PGUSER=django
    - PGPASSWORD=django
install:
    - pip install pipenv
    - pipenv install --dev
before_script:
    - psql -c 'create database yakutiatripp;'
    - psql -c 'create role django with password django'
    - ./manage.py migrate
script:
    - coverage run --source=news,services,tours,reviews --omit="*tests*","*migrations*","*__init__*","*apps.py","*admin.py" manage.py test
after_success:
    - coveralls
