language: python
python:
    - "3.9"
install:
    - pip install pipenv
    - pipenv install --dev
    - ./manage.py migrate
script:
    - coverage run --source=news,services,tours,reviews --omit="*tests*","*migrations*","*__init__*","*apps.py","*admin.py" manage.py test
after_success:
    - coveralls
