language: python
python:
    - "3.9"
env:
    - DJANGO_SECRET_KEY="#bi^q(lytip$+3bj-z-23@6tds)5$fsgi0t^8m_(yg%8rjobc*"
install:
    - pip install pipenv
    - pipenv install --dev
    - ./manage.py migrate
script:
    - coverage run --source=news,services,tours,reviews --omit="*tests*","*migrations*","*__init__*","*apps.py","*admin.py" manage.py test
after_success:
    - coveralls
