version: "3.9"

services:
    web:
        env_file:
            - .env
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_DB=yakutiatripp
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=django
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
