# Generated by Django 3.1.7 on 2021-03-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210307_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-pub_date',), 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
