# Generated by Django 3.1.7 on 2021-03-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210307_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-pub_date', 'title'), 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
