# Generated by Django 3.1.7 on 2021-03-14 09:52
import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(default='/reviews/default_review_avatar.jpg', upload_to='reviews')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('text', models.CharField(max_length=4000)),
                ('moderated', models.BooleanField(default=False)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-moderated', '-rating', '-pub_date'),
            },
        ),
    ]
