openapi: 3.0.2
info:
  title: 'YakutiaTripp API'
  version: '1.0.0'
paths:
  /api/news/:
    get:
      operationId: listAllNews
      description: Return all news list
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNews'
          description: ''
      tags:
      - news
  /api/news/{news_pk}/:
    get:
      operationId: concreteNews
      description: Return a concrete news
      parameters:
      - name: news_pk
        in: path
        required: true
        description: "UUID of news"
        schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
          description: ''
      tags:
      - news
  /api/news/last/:
    get:
      operationId: listLastNews
      description: "Return last 9 news"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNews'
          description: ''
      tags:
      - news
  /api/tours/:
    get:
      operationId: listAllTours
      description: Return all tours
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTour'
          description: ''
      tags:
      - tours
  /api/tours/{tour_pk}/:
    get:
      operationId: concreteTour
      description: Return a concrete tour
      parameters:
      - name: tour_pk
        in: path
        required: true
        description: "UUID of tour"
        schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
          description: ''
      tags:
      - tours
  /api/tours/most_viewed/:
    get:
      operationId: listMostViewedTours
      description: "Return 9 most viewed tours"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTour'
          description: ''
      tags:
      - tours
  /api/tours/search/{city_from}/{city_to}/{date}/:
    get:
      operationId: listSearchedTours
      description: "Returns searched tours with `city_from`, `city_to`, and `date` weekday field"
      parameters:
      - name: city_from
        in: path
        required: true
        description: "city where tour will be started"
        schema:
            type: string
      - name: city_to
        in: path
        required: true
        description: "city where tour will be finished"
        schema:
            type: string
      - name: date
        in: path
        required: true
        description: "date when tour will be started in ISO format (YYYY-MM-DD)"
        schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTour'
          description: ''
      tags:
      - tours
  /api/reviews/:
    get:
      operationId: listAllReviews
      description: Return all moderated reviews
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListReview'
          description: ''
      tags:
      - reviews
    post:
      operationId: createReview
      description: Create a new review
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Review'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                    rating:
                        type: array
                        items:
                            type: string
                            example:
                                "Ensure this value is less than or equal to 5."
      tags:
      - reviews
  /api/reviews/{review_pk}/:
    patch:
      operationId: setReviewAvatar
      description: 'Set a review avatar using PATCH request. In request you
      need to include the file, and in headers you need to include the header
      `Content-Disposition: attachment; filename="filename.jpg"`'
      parameters:
      - name: review_pk
        in: path
        required: true
        description: "UUID of review"
        schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                    avatar:
                        type: string
                        example: "/media/reviews/filename.jpg"
      tags:
      - reviews
components:
    schemas:
        News:
            type: object
            properties:
                pk:
                    type: string
                    example: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                    minLength: 36
                    maxLength: 36
                    description: "UUID primary key of news entry"
                title:
                    type: string
                    maxLength: 255
                    minLength: 1
                    example: Some title
                    description: "Title of news"
                preview:
                    type: string
                    example: "/media/news/image.jpg"
                    description: "Path to image on news preview"
                text:
                    type: string
                    example: "some text"
                    description: "Text of news"
                pub_date:
                    type: string
                    format: date
                    description: "News publication date in ISO format"
        ListNews:
            type: array
            items:
                $ref: '#/components/schemas/News'
        Tour:
            type: object
            properties:
                pk:
                    type: string
                    example: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                    maxLength: 36
                    minLength: 36
                    description: "UUID primary key of tour"
                title:
                    type: string
                    example: Some title
                    maxLength: 255
                    minLength: 1
                    description: "Title of tour"
                preview:
                    type: string
                    example: "/media/tours/image.jpg"
                    description: "Path to image on tour preview"
                short_description:
                    type: string
                    maxLength: 4000
                    minLength: 1
                    example: "Some short description"
                    description: "Tour short description: what is this tour?"
                days:
                    type: array
                    description: "Tour days"
                    items:
                        type: object
                        properties:
                            weekday:
                                type: string
                                maxLength: 9
                                minLength: 1
                                example: Monday
                                description: "Tour day weekday choice from 7 variants:
                                Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday"
                            description:
                                type: string
                                example: Some description
                                description: "Tour day description: what will happen in this day"
                about:
                    type: string
                    minLength: 1
                    example: "Some about"
                    description: "Full description about this tour"
                price:
                    type: string
                    format: decimal
                    description: "Decimal price in format: 100.00, max value: 99999999.99"
                city_from:
                    type: string
                    maxLength: 255
                    minLength: 1
                    example: "Moscow"
                    description: "City where tour will be started"
                city_to:
                    type: string
                    maxLength: 255
                    minLength: 1
                    example: Moscow
                    description: "City where tour will be finished"
                views:
                    type: integer
                    format: int32
                    description: "Number of views of the tour"
        ListTour:
            type: array
            items:
                $ref: '#/components/schemas/Tour'
        Review:
            type: object
            properties:
                pk:
                    type: string
                    minLength: 36
                    maxLength: 36
                    readOnly: true
                    example: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                    description: "UUID primary key of review"
                name:
                    type: string
                    maxLength: 255
                    minLength: 1
                    example: "Author"
                    description: "Name of person who creates a review"
                avatar:
                    type: string
                    example: "/media/reviews/image.jpg"
                    readOnly: true
                    description: "Path to review author avatar"
                rating:
                    type: int
                    format: int32
                    example: 5
                    description: "Review rating in range from 1 to 5"
                text:
                    type: string
                    maxLength: 4000
                    minLength: 1
                    example: Some text
                    description: "Text of review"
                moderated:
                    type: boolean
                    example: true
                    readOnly: true
                    description: "Boolean field is review moderated"
                pub_date:
                    type: string
                    format: date
                    readOnly: true
                    description: "Review publication date"
        ListReview:
            type: array
            items:
                $ref: '#/components/schemas/Review'
