openapi: 3.0.2
info:
  title: 'YakutiaTripp API'
  version: '1.0.0'
paths:
  /api/news/:
    get:
      operationId: listAllNews
      description: Return all news
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                - pk: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                  title: Some title
                  preview: "/media/news/image.jpg"
                  text: Some text
                  pub_date: "2021-03-06"
          description: ''
      tags:
      - news
  /api/news/{news_pk}/:
    get:
      operationId: concreteNews
      description: Return a concrete news
      parameters:
      - name: news_pk
        in: path
        required: true
        description: "UUID of news"
        schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                items: {}
                example:
                  pk: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                  title: Some title
                  preview: "/media/news/image.jpg"
                  text: Some text
                  pub_date: "2021-03-06"
          description: ''
      tags:
      - news
  /api/news/last/:
    get:
      operationId: listLastNews
      description: "Return last 9 news"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                - pk: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                  title: Some title
                  preview: "/media/news/image.jpg"
                  text: Some text
                  pub_date: "2021-03-06"
          description: ''
      tags:
      - news
  /api/tours/:
    get:
      operationId: listAllTours
      description: Return all tours
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                - pk: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                  title: Some title
                  preview: "/media/tours/image.jpg"
                  short_description: Some short description
                  days:
                  - weekday: Monday
                    description: Some description
                  about: Some about
                  price: "100.00"
                  city_from: "Moscow"
                  city_to: "Moscow"
                  views: 0
          description: ''
      tags:
      - tours
  /api/tours/{tour_pk}/:
    get:
      operationId: concreteTour
      description: Return a concrete tour
      parameters:
      - name: tour_pk
        in: path
        required: true
        description: "UUID of tour"
        schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                items: {}
                example:
                  pk: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                  title: Some title
                  preview: "/media/tours/image.jpg"
                  short_description: Some short description
                  days:
                  - weekday: Monday
                    description: Some description
                  about: Some about
                  price: "100.00"
                  city_from: "Moscow"
                  city_to: "Moscow"
                  views: 1
          description: ''
      tags:
      - tours
  /api/tours/most_viewed/:
    get:
      operationId: listMostViewedTours
      description: "Return 9 most viewed tours"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                - pk: "2668b035-ef3d-4415-a68c-00965d75c2ef"
                  title: Some title
                  preview: "/media/tours/image.jpg"
                  short_description: Some short description
                  days:
                  - weekday: Monday
                    description: Some description
                  about: Some about
                  price: "100.00"
                  city_from: "Moscow"
                  city_to: "Moscow"
                  views: 0
          description: ''
      tags:
      - tours
