openapi: 3.0.2
info:
  title: 'YakutiaTripp API'
  version: '1.0.0'
paths:
  /api/news/:
    get:
      operationId: listAllNews
      description: Return all news
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                - title: Some title
                  preview: "/media/news/image.jpg"
                  text: Some text
                  pub_date: "2021-03-06"
          description: ''
      tags:
      - api
